---
- name: set tuned profile
  shell: tuned-adm profile latency-performance

# Here we use a state changed as an indicator of a new install
- name: Install the release CLC packages
  yum: name=eucalyptus-cloud state=latest enablerepo=eucalyptus-release,euca2ools-release,elrepo,epel,base,updates
  when: not nightlies

- name: Install the nightly CLC packages
  yum: name=eucalyptus-cloud state=latest enablerepo=eucalyptus-nightly,euca2ools-release,elrepo,epel,base,updates
  when: nightlies

- name: Template the configuration file
  template: src=../../common/templates/eucalyptus.conf.j2 dest=/etc/eucalyptus/eucalyptus.conf

# Only initialize the database if packages were installed
# (its a new environment)
- name: Initialize the database
  shell: /usr/sbin/euca_conf --initialize creates=/var/lib/eucalyptus/keys/euca.p12
  register: init

- name: Restart CLC
  service: name=eucalyptus-cloud state=restarted
  when: init.changed

- name: Start CLC
  service: name=eucalyptus-cloud state=started

# Wait for services to come up
- name: Waiting for CLC services
  wait_for: port=8777

# Before we register commands, we need to copy move keys around.
- name: Fetch cloud keys
  fetch: src=/var/lib/eucalyptus/keys/{{ item }} dest=/tmp/ flat=yes
  with_items:
  - cloud-cert.pem
  - cloud-pk.pem
  - euca.p12
