---

- hosts: dmccue
  remote_user: deploy
  become: true
  gather_facts: no
  vars:
    - euca_release: 4.1
    - euca2ools_release: 3.2
  tasks:
    # - name: add repos - epel,euca,euca2ools
    #   yum: state=present name={{ item }}
    #   with_items:
    #     - http://downloads.eucalyptus.com/software/eucalyptus/{{ euca_release }}/centos/6/x86_64/epel-release-6.noarch.rpm
    #     - http://downloads.eucalyptus.com/software/eucalyptus/{{ euca_release }}/centos/6/x86_64/eucalyptus-release-{{ euca_release }}.el6.noarch.rpm
    #     - http://downloads.eucalyptus.com/software/euca2ools/{{ euca2ools_release }}/centos/6/x86_64/euca2ools-release-{{ euca2ools_release }}.el6.noarch.rpm
    #   register: repo_result
    # - name: yum clean
    #   command: yum clean all
    #   when: repo_result.changed
    # - name: update all packages
    #   yum: name=* state=latest
    # - name: selinux python libs
    #   yum: name=libselinux-python state=latest
    # - name: set selinux to permissive
      selinux: policy=targeted state=permissive
      notify: restart server
    # - name: iptables off
    #   service: name=iptables state=stopped enabled=false
    # - name: ntpd service
    #   yum: state=present name=ntp
    # - name: ntpd started
    #   service: name=ntpd state=started enabled=true
    - name: clock sync
      shell: hwclock --systohc
  handlers:
    - include: handlers/handlers.yml




#- hosts: localhost
#  gather_facts: no
#  tasks:
#    - shell: git clone https://github.com/eucalyptus/playbook.git || { cd playbook; git pull; }
#- name: Build hosts file
#  local_action: lineinfile dest=hosts
#                regexp='^{{ item }}$'
#                line="{{ item }}"
#                state=present
#  with_items: groups['dmccue']
#- name: test connection
#  ping:
#- name: gather facts
#  setup:
#- name: disable selinux
#  selinux: state=disable
#- name: printall
#  debug: var=hostvars[inventory_hostname][cobbler][name]
#- name: print cobbler id
#  debug: msg="Cobbler ID:{{ cobbler.name }} has Hostname:{{ cobbler.hostname }} and IPaddress:{{ ansible_default_ipv4.address }}"
#- hosts: localhost
#  gather_facts: no
#  tasks:
#    - shell: echo $(date) > test
